/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

/**
 *
 * @author dario
 */
public class VentanaAPP extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAPP
     */
    public VentanaAPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        botonConsulta = new javax.swing.JButton();
        botonInsercion = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonBorrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(48, 56, 65));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(80, 82, 84));
        PanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 670, -1));

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 173, 181));
        titulo.setText("CREA, INSERTA O MODIFICA FACTURAS");
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPrincipal.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 720, 60));

        botonConsulta.setBackground(new java.awt.Color(255, 75, 0));
        botonConsulta.setFont(new java.awt.Font("Liberation Sans", 1, 33)); // NOI18N
        botonConsulta.setForeground(new java.awt.Color(238, 238, 238));
        botonConsulta.setText("Consultar datos");
        botonConsulta.setBorder(null);
        botonConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPrincipal.add(botonConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, 150));

        botonInsercion.setBackground(new java.awt.Color(255, 75, 0));
        botonInsercion.setFont(new java.awt.Font("Liberation Sans", 1, 33)); // NOI18N
        botonInsercion.setForeground(new java.awt.Color(238, 238, 238));
        botonInsercion.setText("Añadir datos");
        botonInsercion.setBorder(null);
        botonInsercion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsercionActionPerformed(evt);
            }
        });
        PanelPrincipal.add(botonInsercion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 270, 150));

        botonBorrar.setBackground(new java.awt.Color(255, 75, 0));
        botonBorrar.setFont(new java.awt.Font("Liberation Sans", 1, 33)); // NOI18N
        botonBorrar.setForeground(new java.awt.Color(238, 238, 238));
        botonBorrar.setText("Actualizar datos");
        botonBorrar.setBorder(null);
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPrincipal.add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 270, 150));

        botonBorrar1.setBackground(new java.awt.Color(255, 75, 0));
        botonBorrar1.setFont(new java.awt.Font("Liberation Sans", 1, 33)); // NOI18N
        botonBorrar1.setForeground(new java.awt.Color(238, 238, 238));
        botonBorrar1.setText("Borrar datos");
        botonBorrar1.setBorder(null);
        botonBorrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPrincipal.add(botonBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 270, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInsercionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {               
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrar1;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonInsercion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
