/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import controllers.FacturaJpaController;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author dario
 */
public class VentanaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaActualizar
     */
    public VentanaBuscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        botonRegresar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        codigoJLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        facturaJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(48, 56, 65));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.setBackground(new java.awt.Color(255, 75, 0));
        botonRegresar.setFont(new java.awt.Font("Liberation Sans", 1, 33)); // NOI18N
        botonRegresar.setForeground(new java.awt.Color(238, 238, 238));
        botonRegresar.setText("Regresar");
        botonRegresar.setBorder(null);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresarMouseClicked(evt);
            }
        });
        PanelPrincipal.add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 270, 110));

        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 173, 181));
        titulo.setText("ACTUALIZA FACTURAS");
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPrincipal.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 420, 60));

        codigoJLabel.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        codigoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        codigoJLabel.setText("- Codigo:");
        PanelPrincipal.add(codigoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, -1));

        codigoTextField.setBackground(new java.awt.Color(255, 255, 255));
        codigoTextField.setForeground(new java.awt.Color(0, 0, 0));
        PanelPrincipal.add(codigoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 270, 50));

        botonActualizar.setBackground(new java.awt.Color(255, 75, 0));
        botonActualizar.setFont(new java.awt.Font("Liberation Sans", 1, 33)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(238, 238, 238));
        botonActualizar.setText("Buscar");
        botonActualizar.setBorder(null);
        botonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarMouseClicked(evt);
            }
        });
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 270, 110));

        facturaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.add(facturaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresarMouseClicked
        // TODO add your handling code here:
        VentanaInicio ventanaInicio = new VentanaInicio();
        ventanaInicio.setVisible(true);
        ventanaInicio.setLocationRelativeTo(null);
        ventanaInicio.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_botonRegresarMouseClicked

    private void botonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarMouseClicked

    // Cuando le damos al botón de actualizar
    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("p82dario");
        FacturaJpaController control = new FacturaJpaController(emf);
        
        int pk = Integer.parseInt(codigoTextField.getText());
        
        try {
            facturaJLabel.setText(control.findFactura(pk).toString());            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha habido un error buscando esta factura");
        }
        
        
    }//GEN-LAST:event_botonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel codigoJLabel;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel facturaJLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
